### ISSUE TITLE
COMPILATION ERROR CCATest

### ISSUE THREAD

**Issue by GlcBrero** [marketdesignresearch/mechlib#1]
[ERROR] mechlib-master/src/test/java/org/marketdesignresearch/mechlib/mechanism/auctions/cca/CCATest.java:[292,58] method containsExactlyInAnyOrder in class org.assertj.core.api.IterableAssert<ELEMENT> cannot be applied to given types;
  required: capture#1 of ? extends org.marketdesignresearch.mechlib.core.bidder.Bidder[]
  found: org.marketdesignresearch.mechlib.core.bidder.ORBidder,org.marketdesignresearch.mechlib.core.bidder.ORBidder
  reason: varargs mismatch; org.marketdesignresearch.mechlib.core.bidder.ORBidder cannot be converted to capture#1 of ? extends org.marketdesignresearch.mechlib.core.bidder.Bidder
[ERROR] mechlib-master/src/test/java/org/marketdesignresearch/mechlib/mechanism/auctions/cca/CCATest.java:[352,44] method containsExactlyInAnyOrder in class org.assertj.core.api.IterableAssert<ELEMENT> cannot be applied to given types;
  required: capture#2 of ? extends org.marketdesignresearch.mechlib.core.bidder.Bidder[]
  found: org.marketdesignresearch.mechlib.core.bidder.ORBidder,org.marketdesignresearch.mechlib.core.bidder.ORBidder
  reason: varargs mismatch; org.marketdesignresearch.mechlib.core.bidder.ORBidder cannot be converted to capture#2 of ? extends org.marketdesignresearch.mechlib.core.bidder.Bidder

**Comment by islerfab** [comment]
Fixed in 73a2e72daf384fe143402cecd932fd0244a40c26.
